alias on="source .venv/bin/activate"
alias off="deactivate"
alias pythonNG="/home/jpsca/.asdf/installs/python/nogil-3.9.10/bin/python"
alias mkenv10="python3.10 -m venv .venv && on && pip install -U pip wheel"
alias mkenv9="python3.9 -m venv .venv && on && pip install -U pip wheel"
alias mkenv8="python3.8 -m venv .venv && on && pip install -U pip wheel"
alias mkenv7="python3.7 -m venv .venv && on && pip install -U pip wheel"
alias mkenvNG="pythonNG -m venv .venv && on && pip install -U pip wheel"
